repos:

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    - id: check-json
    - id: check-yaml
    - id: end-of-file-fixer
    - id: trailing-whitespace
      exclude:
        ".xml"

  - repo: https://github.com/mgedmin/check-manifest
    rev: "0.50"
    hooks:
    - id: check-manifest

  - repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
    - id: black

  - repo: https://github.com/PyCQA/pylint
    rev: v3.3.1
    hooks:
    - id: pylint
      args:
        - --disable=missing-docstring,similarities,fixme
      additional_dependencies:
        - sphinx
        - docutils
        - pygments
      exclude: >
        (?x)^(
          setup.py|
          tests/.*|
          docs/.*
        )$
