version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3"

python:
  install:
      - method: pip
        path: .

sphinx:
  configuration: docs/conf.py
  builder: html
  fail_on_warning: true

formats:
  - pdf
