# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: continuous-integration

on:
  push:
    branches: [main]
    tags:
      - 'v*'
  pull_request:
  # Run weekly to check for breaking changes in unpinned dependencies
  schedule:
    - cron: '0 18 * * 5'

jobs:

  py-tests:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13", "3.14"]

    steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0  # v7.0.0
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405  # v6.2.0
      with:
        python-version: ${{ matrix.python-version }}
        allow-prereleases: true
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .[testing]
    - name: Run pytest
      run: |
        pytest --cov=sphinx_tabs --cov-report=xml --cov-report=term-missing

  js-tests:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0  # v7.0.0
    - name: Use Node.js 15
      uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e  # v6.4.0
      with:
        node-version: '15'
    - name: Install jest
      run: npm install jest@26.6.3
    - name: Run JS tests
      run: npm test

  publish:

    name: Publish to PyPi
    needs: [py-tests, js-tests]
    if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags')
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source
      uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0  # v7.0.0
    - name: Set up Python 3.12
      uses: actions/setup-python@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e  # v6.4.0
      with:
        python-version: 3.12
    - name: Build package
      run: |
        python -m pip install -U pip build
        python -m build --sdist --wheel .
    - name: Publish
      uses: pypa/gh-action-pypi-publish@cef221092ed1bacb1cc03d23a2d87d1d172e277b  # v1.14.0
      with:
        user: __token__
        password: ${{ secrets.PYPI_KEY }}
